name: Run Prediction Script

on:
  workflow_dispatch: # Manual trigger

jobs:
  run-predictions:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy tensorflow

    # Step 4: Run the prediction script
    - name: Run Prediction Script
      run: |
        python predict_rnn.py
